Repository bla-bla-Notion/frontend, pull requests merged in 2022-12, with the labels that each got.

#7 MainPage 유저 닉네임 출력, 삭제, 닉네임 출력 컴포넌트 생성 #6
  src/components/userItem.js
  src/pages/MainPage.js
Labels: frontend, FEAT

#11 Header MainPage Nickname Component Style change
  src/App.js
  src/components/Header.js
  src/components/Layout.js
  src/components/userItem.js
  src/pages/MainPage.js
  src/shared/Routes.js
Labels: frontend, FEAT, design

#18 Jsg
  public/index.html
  src/components/Layout.js
  src/pages/MainPage.js
  src/pages/PostDetailPage.js
  src/redux/modules/PostsSlice.js
  src/shared/api.js
Labels: frontend, FEAT, design

#24 Jsg
  README.md
  src/components/Header.js
  src/pages/MainPage.js
  src/pages/PostDetailPage.js
  src/redux/config/configStore.js
Labels: frontend, FEAT, design

#35 Jsg
  src/components/Header.js
  src/components/Modal.js
  src/pages/MainPage.js
  src/pages/PostDetailPage.js
  src/redux/config/configStore.js
  src/redux/modules/PostsSlice.js
Labels: frontend, FEAT, design

#36 Pre summit
  README.md
  package.json
  public/favicon.ico
  public/index.html
  src/App.js
  src/components/Header.js
  src/components/Layout.js
  src/components/Modal.js
  src/components/userItem.js
  src/index.js
  src/pages/MainPage.js
  src/pages/PostDetailPage.js
  src/pages/snow.css
  src/redux/config/configStore.js
  src/redux/modules/PostsSlice.js
  src/shared/Routes.js
  src/shared/api.js
  yarn.lock
Labels: complete
